# Generated by Django 4.2.3 on 2023-08-11 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logadm', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Usuarioa',
        ),
    ]
