# Generated by Django 4.2.3 on 2023-08-10 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamado', '0002_chamado_data_cadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='data_cadastro',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
