# Generated by Django 4.2.3 on 2023-08-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamado', '0003_alter_chamado_data_cadastro'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='status',
            field=models.CharField(default='Pendente', max_length=40),
        ),
    ]
