# Generated by Django 4.2.3 on 2023-08-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamado', '0004_chamado_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='data_finalizado',
            field=models.CharField(default='N/A', max_length=12),
        ),
    ]
