# Generated by Django 4.2.3 on 2023-08-15 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logadm', '0002_rename_usuario_usuarioa'),
        ('chamado', '0007_chamado_tecnico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='tecnico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='logadm.usuarioa'),
        ),
    ]
