# Generated by Django 4.2.3 on 2023-08-16 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamado', '0008_alter_chamado_tecnico'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='unidade',
            field=models.CharField(default='N/A', max_length=65),
        ),
    ]
