# Generated by Django 4.2.3 on 2023-08-16 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamado', '0009_chamado_unidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='solucao',
            field=models.CharField(default='N/A', max_length=399),
        ),
    ]
